[general]
import = [ "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml" ]

[window]
dimensions = { columns = 150, lines = 40 }
padding = { x = 10, y = 10 }
opacity = 0.8
startup_mode = "Maximized"
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 13

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_timeout = 0

[mouse]
hide_when_typing = true

