# Change Default Prefix
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Change Vertical & Horizontal Split
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# Reload .tmux.conf File
unbind r
bind r source-file ~/.tmux.conf

# Resize panes using Vim-style keys
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Toggle zoom for the current pane
bind -r m resize-pane -Z

# Enable Mouse
set -g mouse on

# Start window numbering at 1 instead of the default 0
set -g base-index 1

# Start pane numbering at 1 instead of the default 0
set -g pane-base-index 1

# Automatically renumber windows after one is closed
set -g renumber-windows on

# TMUX Plugin Manager
set -g @plugin 'tmux-plugins/tpm'

# TMUX Plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

# Catpuccin Theme styles
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_status_style "rounded"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# TMUX Plugin Initializer (At the end of the file)
run '~/.tmux/plugins/tpm/tpm'
